version: "3"
services:
  db:
    container_name: rails_boilerplate_db
    image: postgres:15.4
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - rails_boilerplate_development:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rails_boilerplate_development
    ports:
      - 5432:5432

  redis:
    container_name: rails_boilerplate_redis
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  rails_boilerplate_development:
    name: rails_boilerplate_development