default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_DB'] || 'rails_boilerplate' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_DB'] || 'rails_boilerplate' %>
  username: <%= ENV['TEST_DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] || 'postgres' %>
  host: <%= ENV['TEST_DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['TEST_DATABASE_PORT'] || '5432' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_DB'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
